/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PharmacyOdsCodeRouteImport } from './routes/pharmacy.$odsCode'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMyAnalysesRouteImport } from './routes/_authenticated/my-analyses'
import { Route as AuthenticatedLeaderboardsRouteImport } from './routes/_authenticated/leaderboards'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedIncomeRouteImport } from './routes/_authenticated/income'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompareRouteImport } from './routes/_authenticated/compare'
import { Route as AuthenticatedBenchmarkingRouteImport } from './routes/_authenticated/benchmarking'
import { Route as AuthenticatedAdminPaymentsImportRouteImport } from './routes/_authenticated/admin.payments-import'
import { Route as AuthenticatedAdminDataRouteImport } from './routes/_authenticated/admin.data'
import { Route as AuthenticatedAcquisitionOdsCodeRouteImport } from './routes/_authenticated/acquisition.$odsCode'
import { Route as ApiPublicIngestPharmacyPaymentsRouteImport } from './routes/api/public/ingest.pharmacy-payments'
import { Route as ApiPublicHooksIngestScotlandRouteImport } from './routes/api/public/hooks/ingest-scotland'
import { Route as ApiPublicHooksIngestNiRouteImport } from './routes/api/public/hooks/ingest-ni'
import { Route as ApiPublicHooksIngestEnglandRouteImport } from './routes/api/public/hooks/ingest-england'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyOdsCodeRoute = PharmacyOdsCodeRouteImport.update({
  id: '/pharmacy/$odsCode',
  path: '/pharmacy/$odsCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyAnalysesRoute = AuthenticatedMyAnalysesRouteImport.update({
  id: '/my-analyses',
  path: '/my-analyses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardsRoute =
  AuthenticatedLeaderboardsRouteImport.update({
    id: '/leaderboards',
    path: '/leaderboards',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomeRoute = AuthenticatedIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompareRoute = AuthenticatedCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBenchmarkingRoute =
  AuthenticatedBenchmarkingRouteImport.update({
    id: '/benchmarking',
    path: '/benchmarking',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPaymentsImportRoute =
  AuthenticatedAdminPaymentsImportRouteImport.update({
    id: '/admin/payments-import',
    path: '/admin/payments-import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDataRoute = AuthenticatedAdminDataRouteImport.update({
  id: '/admin/data',
  path: '/admin/data',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAcquisitionOdsCodeRoute =
  AuthenticatedAcquisitionOdsCodeRouteImport.update({
    id: '/acquisition/$odsCode',
    path: '/acquisition/$odsCode',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicIngestPharmacyPaymentsRoute =
  ApiPublicIngestPharmacyPaymentsRouteImport.update({
    id: '/api/public/ingest/pharmacy-payments',
    path: '/api/public/ingest/pharmacy-payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIngestScotlandRoute =
  ApiPublicHooksIngestScotlandRouteImport.update({
    id: '/api/public/hooks/ingest-scotland',
    path: '/api/public/hooks/ingest-scotland',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIngestNiRoute = ApiPublicHooksIngestNiRouteImport.update({
  id: '/api/public/hooks/ingest-ni',
  path: '/api/public/hooks/ingest-ni',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIngestEnglandRoute =
  ApiPublicHooksIngestEnglandRouteImport.update({
    id: '/api/public/hooks/ingest-england',
    path: '/api/public/hooks/ingest-england',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/benchmarking': typeof AuthenticatedBenchmarkingRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/income': typeof AuthenticatedIncomeRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/leaderboards': typeof AuthenticatedLeaderboardsRoute
  '/my-analyses': typeof AuthenticatedMyAnalysesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/pharmacy/$odsCode': typeof PharmacyOdsCodeRoute
  '/acquisition/$odsCode': typeof AuthenticatedAcquisitionOdsCodeRoute
  '/admin/data': typeof AuthenticatedAdminDataRoute
  '/admin/payments-import': typeof AuthenticatedAdminPaymentsImportRoute
  '/api/public/hooks/ingest-england': typeof ApiPublicHooksIngestEnglandRoute
  '/api/public/hooks/ingest-ni': typeof ApiPublicHooksIngestNiRoute
  '/api/public/hooks/ingest-scotland': typeof ApiPublicHooksIngestScotlandRoute
  '/api/public/ingest/pharmacy-payments': typeof ApiPublicIngestPharmacyPaymentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/benchmarking': typeof AuthenticatedBenchmarkingRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/income': typeof AuthenticatedIncomeRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/leaderboards': typeof AuthenticatedLeaderboardsRoute
  '/my-analyses': typeof AuthenticatedMyAnalysesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/pharmacy/$odsCode': typeof PharmacyOdsCodeRoute
  '/acquisition/$odsCode': typeof AuthenticatedAcquisitionOdsCodeRoute
  '/admin/data': typeof AuthenticatedAdminDataRoute
  '/admin/payments-import': typeof AuthenticatedAdminPaymentsImportRoute
  '/api/public/hooks/ingest-england': typeof ApiPublicHooksIngestEnglandRoute
  '/api/public/hooks/ingest-ni': typeof ApiPublicHooksIngestNiRoute
  '/api/public/hooks/ingest-scotland': typeof ApiPublicHooksIngestScotlandRoute
  '/api/public/ingest/pharmacy-payments': typeof ApiPublicIngestPharmacyPaymentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/benchmarking': typeof AuthenticatedBenchmarkingRoute
  '/_authenticated/compare': typeof AuthenticatedCompareRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/income': typeof AuthenticatedIncomeRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/leaderboards': typeof AuthenticatedLeaderboardsRoute
  '/_authenticated/my-analyses': typeof AuthenticatedMyAnalysesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/pharmacy/$odsCode': typeof PharmacyOdsCodeRoute
  '/_authenticated/acquisition/$odsCode': typeof AuthenticatedAcquisitionOdsCodeRoute
  '/_authenticated/admin/data': typeof AuthenticatedAdminDataRoute
  '/_authenticated/admin/payments-import': typeof AuthenticatedAdminPaymentsImportRoute
  '/api/public/hooks/ingest-england': typeof ApiPublicHooksIngestEnglandRoute
  '/api/public/hooks/ingest-ni': typeof ApiPublicHooksIngestNiRoute
  '/api/public/hooks/ingest-scotland': typeof ApiPublicHooksIngestScotlandRoute
  '/api/public/ingest/pharmacy-payments': typeof ApiPublicIngestPharmacyPaymentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/benchmarking'
    | '/compare'
    | '/dashboard'
    | '/income'
    | '/insights'
    | '/leaderboards'
    | '/my-analyses'
    | '/settings'
    | '/upload'
    | '/pharmacy/$odsCode'
    | '/acquisition/$odsCode'
    | '/admin/data'
    | '/admin/payments-import'
    | '/api/public/hooks/ingest-england'
    | '/api/public/hooks/ingest-ni'
    | '/api/public/hooks/ingest-scotland'
    | '/api/public/ingest/pharmacy-payments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/benchmarking'
    | '/compare'
    | '/dashboard'
    | '/income'
    | '/insights'
    | '/leaderboards'
    | '/my-analyses'
    | '/settings'
    | '/upload'
    | '/pharmacy/$odsCode'
    | '/acquisition/$odsCode'
    | '/admin/data'
    | '/admin/payments-import'
    | '/api/public/hooks/ingest-england'
    | '/api/public/hooks/ingest-ni'
    | '/api/public/hooks/ingest-scotland'
    | '/api/public/ingest/pharmacy-payments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/benchmarking'
    | '/_authenticated/compare'
    | '/_authenticated/dashboard'
    | '/_authenticated/income'
    | '/_authenticated/insights'
    | '/_authenticated/leaderboards'
    | '/_authenticated/my-analyses'
    | '/_authenticated/settings'
    | '/_authenticated/upload'
    | '/pharmacy/$odsCode'
    | '/_authenticated/acquisition/$odsCode'
    | '/_authenticated/admin/data'
    | '/_authenticated/admin/payments-import'
    | '/api/public/hooks/ingest-england'
    | '/api/public/hooks/ingest-ni'
    | '/api/public/hooks/ingest-scotland'
    | '/api/public/ingest/pharmacy-payments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PharmacyOdsCodeRoute: typeof PharmacyOdsCodeRoute
  ApiPublicHooksIngestEnglandRoute: typeof ApiPublicHooksIngestEnglandRoute
  ApiPublicHooksIngestNiRoute: typeof ApiPublicHooksIngestNiRoute
  ApiPublicHooksIngestScotlandRoute: typeof ApiPublicHooksIngestScotlandRoute
  ApiPublicIngestPharmacyPaymentsRoute: typeof ApiPublicIngestPharmacyPaymentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/$odsCode': {
      id: '/pharmacy/$odsCode'
      path: '/pharmacy/$odsCode'
      fullPath: '/pharmacy/$odsCode'
      preLoaderRoute: typeof PharmacyOdsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-analyses': {
      id: '/_authenticated/my-analyses'
      path: '/my-analyses'
      fullPath: '/my-analyses'
      preLoaderRoute: typeof AuthenticatedMyAnalysesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboards': {
      id: '/_authenticated/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof AuthenticatedLeaderboardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/income': {
      id: '/_authenticated/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AuthenticatedIncomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compare': {
      id: '/_authenticated/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthenticatedCompareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/benchmarking': {
      id: '/_authenticated/benchmarking'
      path: '/benchmarking'
      fullPath: '/benchmarking'
      preLoaderRoute: typeof AuthenticatedBenchmarkingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/payments-import': {
      id: '/_authenticated/admin/payments-import'
      path: '/admin/payments-import'
      fullPath: '/admin/payments-import'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/data': {
      id: '/_authenticated/admin/data'
      path: '/admin/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AuthenticatedAdminDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/acquisition/$odsCode': {
      id: '/_authenticated/acquisition/$odsCode'
      path: '/acquisition/$odsCode'
      fullPath: '/acquisition/$odsCode'
      preLoaderRoute: typeof AuthenticatedAcquisitionOdsCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/ingest/pharmacy-payments': {
      id: '/api/public/ingest/pharmacy-payments'
      path: '/api/public/ingest/pharmacy-payments'
      fullPath: '/api/public/ingest/pharmacy-payments'
      preLoaderRoute: typeof ApiPublicIngestPharmacyPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-scotland': {
      id: '/api/public/hooks/ingest-scotland'
      path: '/api/public/hooks/ingest-scotland'
      fullPath: '/api/public/hooks/ingest-scotland'
      preLoaderRoute: typeof ApiPublicHooksIngestScotlandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-ni': {
      id: '/api/public/hooks/ingest-ni'
      path: '/api/public/hooks/ingest-ni'
      fullPath: '/api/public/hooks/ingest-ni'
      preLoaderRoute: typeof ApiPublicHooksIngestNiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-england': {
      id: '/api/public/hooks/ingest-england'
      path: '/api/public/hooks/ingest-england'
      fullPath: '/api/public/hooks/ingest-england'
      preLoaderRoute: typeof ApiPublicHooksIngestEnglandRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBenchmarkingRoute: typeof AuthenticatedBenchmarkingRoute
  AuthenticatedCompareRoute: typeof AuthenticatedCompareRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIncomeRoute: typeof AuthenticatedIncomeRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedLeaderboardsRoute: typeof AuthenticatedLeaderboardsRoute
  AuthenticatedMyAnalysesRoute: typeof AuthenticatedMyAnalysesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedAcquisitionOdsCodeRoute: typeof AuthenticatedAcquisitionOdsCodeRoute
  AuthenticatedAdminDataRoute: typeof AuthenticatedAdminDataRoute
  AuthenticatedAdminPaymentsImportRoute: typeof AuthenticatedAdminPaymentsImportRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBenchmarkingRoute: AuthenticatedBenchmarkingRoute,
  AuthenticatedCompareRoute: AuthenticatedCompareRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIncomeRoute: AuthenticatedIncomeRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedLeaderboardsRoute: AuthenticatedLeaderboardsRoute,
  AuthenticatedMyAnalysesRoute: AuthenticatedMyAnalysesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedAcquisitionOdsCodeRoute: AuthenticatedAcquisitionOdsCodeRoute,
  AuthenticatedAdminDataRoute: AuthenticatedAdminDataRoute,
  AuthenticatedAdminPaymentsImportRoute: AuthenticatedAdminPaymentsImportRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PharmacyOdsCodeRoute: PharmacyOdsCodeRoute,
  ApiPublicHooksIngestEnglandRoute: ApiPublicHooksIngestEnglandRoute,
  ApiPublicHooksIngestNiRoute: ApiPublicHooksIngestNiRoute,
  ApiPublicHooksIngestScotlandRoute: ApiPublicHooksIngestScotlandRoute,
  ApiPublicIngestPharmacyPaymentsRoute: ApiPublicIngestPharmacyPaymentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
